### ISSUE TITLE
BUG crazyhouse: After taking the converted pawn, a pawn should be in hand. 

### ISSUE THREAD

**Issue by malaschitz** [alexobviously/bishop#13]
After taking the converted pawn, a pawn should be in hand. In test https://github.com/malaschitz/bishop/blob/master/test/crazy_test.dart The knight takes the queen on h8. A pawn should be added to the hand but the knight is added.

**Comment by malaschitz** [comment]
It solved (at least for Crazyhouse) in https://github.com/malaschitz/bishop/commit/6bcce6a0b9d108dedb4dc7ab2fc78140710f31d5

**Comment by alexobviously** [comment]
Fixed in https://github.com/alexobviously/bishop/commit/34bb7c026ddbcccbe3e921e1f21301e4649c2828
