### ISSUE TITLE
BUG crazyhouse: Pawn drop on first (eight) rank

### ISSUE THREAD

**Issue by malaschitz** [alexobviously/bishop#14]
It is possible now. But it is not according to rules. https://en.wikipedia.org/wiki/Crazyhouse - _A pawn may not be dropped on the 1st or 8th [ranks](https://en.wikipedia.org/wiki/Glossary_of_chess#rank)._

**Comment by malaschitz** [comment]
I solve it with simple check first rank: https://github.com/malaschitz/bishop/commit/7b8e03b56493e91ed6e1332e58f6cd5ad360ad55

**Comment by alexobviously** [comment]
Fixed in https://github.com/alexobviously/bishop/commit/34bb7c026ddbcccbe3e921e1f21301e4649c2828
