### ISSUE TITLE
Mobility Regions

### ISSUE THREAD

**Issue by alexobviously** [alexobviously/bishop#5]
Support for restricting certain piece types to specific areas of the board, for example generals, advisors and elephants in Xiangqi all have their movement restricted to certain areas of the board.

We probably want some `MobilityRegion` class that takes upper and lower rank and file limits, and maybe just check them in `addMove` for simplicity.

**Comment by alexobviously** [comment]
Implemented in `0.6.1` as `BoardRegion` and `RegionEffect`.

**Comment by malaschitz** [comment]
Maybe it could be used for add pawns in crazyhouse ?
