### ISSUE TITLE
Add Images to README

### ISSUE THREAD

**Issue by Erik0806** [alexobviously/bishop#55]
It is much easier to decide if you want to use a package, if there are images in the Readme. Btw your package looks great so far.

**Comment by alexobviously** [comment]
What sort of images would you like? This isn't a UI package so I don't really think there are any images to be had, haha. [Squares](https://pub.dev/packages/squares) does have images though of course.

And glad you like it! If you build anything interesting feel free to share, and if you come across any bugs let me know
