### ISSUE TITLE
Wrong materialConditions for Seirawan

### ISSUE THREAD

**Issue by malaschitz** [alexobviously/bishop#70]
In Seirawan Chess are used another names and letters for Archbishop and Chancellor. There is Hawk and Elephant (H and E). In [material_conditions.dart](https://github.com/alexobviously/bishop/blob/master/lib/src/variant/options/material_conditions.dart) on line 75 should be:

`soloMaters: ['P', 'Q', 'R', 'A', 'C', 'E', 'H'],`

or change the definition of Seirawan chess with customized materialConditions.

**Comment by alexobviously** [comment]
Ah nice, well spotted. I'll include this in the next version.

**Comment by alexobviously** [comment]
Fixed in `1.4.1`, thanks.
