### ISSUE TITLE
Bug for castling in chess960 

### ISSUE THREAD

**Issue by malaschitz** [alexobviously/bishop#72]
On line 436 in [game.dart](https://github.com/alexobviously/bishop/blob/master/lib/src/game/game.dart#L436) is a bug.

For example when in chess960 will be rook on a1 and king on c1, this condition gives incorrect result, because rook is moved from a1 to d1 and c1 is not empty. 

I suggest this correction for condition:

`if (board[midSq].isNotEmpty && midFile != royalFile) {`

**Comment by alexobviously** [comment]
Okay I'll take a look this weekend. The castling stuff is always a bit tricky, so I'll test your suggestion and make sure it works with all the other cases. Btw if you gave me a full fen string for this it would be helpful, for clarity.

**Comment by alexobviously** [comment]
Fixed in `1.4.1`, thanks!
